main: com.linyuanlin.minecraft.App
name: MainSystem
version: 0.1
depend: [ HolographicDisplays, DiscordBotAPI ]
commands:
  team:
    description: 組隊系統
  trade:
    description: 交易系統
  guild:
    description: 公會系統